# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec7d1ca50857ac37d82fa0a528a6db2a291826c58daaa247d5ece18dd3685d352a9d8425800e0c42acc8183a64c649ff2289a1a14b32109601081dbde7833464

test:
  secret_key_base: fdf8d822a7768fba14a8e405a285b8ded236a4d4039029aa6b9d72e85ed97c9d9c703162194a9f59aaa5496ec9c3fd2efc50360a58537df29969418362ebd42a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
